// DON'T CHANGE FOR TESTING
// CHANGE ONLY IF CONTRACT IS MODIFIED
require('dotenv').config()
export const NFT_CONTRACT=process.env.NFT_CONTRACT

// DON'T CHANGE, PERMANENT CONTRACT ADDRESS FROM STORY
export const ROYALTY_POLICY_LAP=process.env.ROYALTY_POLICY_LAP

export const PINATA_API_KEY=process.env.PINATA_API_KEY
export const PINATA_API_SECRET=process.env.PINATA_API_SECRET
export const PINATA_JWT=process.env.PINATA_JWT

